#!/bin/bash

# Script to deploy homepage and proxy on Google App Engine.

# Go to the top level directory of the CodeCityHomepage git
# repository.  It's the directory containing this script.
cd "$(dirname "${BASH_SOURCE[0]}")"

PROJECT=code-city
VERSION=2

echo 'Beginning deployment...'
gcloud app deploy --project $PROJECT --version $VERSION --quiet \
       app.yaml proxy/proxy-service.yaml dispatch.yaml
echo 'Deployment finished.'
