#!/bin/bash

# Script to deploy on GAE, for those not using GoogleAppEngineLauncher

APP=./app.yaml
if ! [ -f $APP ] ; then
   echo $APP not found 1>&2
   exit 1
fi

PROJECT=code-city
VERSION=1

echo 'Beginning deployment...'
gcloud app deploy --project $PROJECT --version $VERSION
echo 'Deployment finished.'
